server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:centraldb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN


