server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:storedb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

store:
  sync:
    centralBaseUrl: http://localhost:8080
    enabled: true
    fixedDelayMs: 900000
    maxRetries: 3
    initialBackoffMs: 200

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

